// Generated by gencpp from file ml_msgs/MarkerDetection.msg
// DO NOT EDIT!


#ifndef ML_MSGS_MESSAGE_MARKERDETECTION_H
#define ML_MSGS_MESSAGE_MARKERDETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ml_msgs/Marker.h>

namespace ml_msgs
{
template <class ContainerAllocator>
struct MarkerDetection_
{
  typedef MarkerDetection_<ContainerAllocator> Type;

  MarkerDetection_()
    : header()
    , markers()  {
    }
  MarkerDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , markers(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ml_msgs::Marker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ml_msgs::Marker_<ContainerAllocator> >::other >  _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::ml_msgs::MarkerDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ml_msgs::MarkerDetection_<ContainerAllocator> const> ConstPtr;

}; // struct MarkerDetection_

typedef ::ml_msgs::MarkerDetection_<std::allocator<void> > MarkerDetection;

typedef boost::shared_ptr< ::ml_msgs::MarkerDetection > MarkerDetectionPtr;
typedef boost::shared_ptr< ::ml_msgs::MarkerDetection const> MarkerDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ml_msgs::MarkerDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ml_msgs::MarkerDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ml_msgs::MarkerDetection_<ContainerAllocator1> & lhs, const ::ml_msgs::MarkerDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.markers == rhs.markers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ml_msgs::MarkerDetection_<ContainerAllocator1> & lhs, const ::ml_msgs::MarkerDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ml_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ml_msgs::MarkerDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ml_msgs::MarkerDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ml_msgs::MarkerDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ml_msgs::MarkerDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ml_msgs::MarkerDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ml_msgs::MarkerDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ml_msgs::MarkerDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98b2dd1b1684e7d642f181b4ca3c1f0c";
  }

  static const char* value(const ::ml_msgs::MarkerDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98b2dd1b1684e7d6ULL;
  static const uint64_t static_value2 = 0x42f181b4ca3c1f0cULL;
};

template<class ContainerAllocator>
struct DataType< ::ml_msgs::MarkerDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ml_msgs/MarkerDetection";
  }

  static const char* value(const ::ml_msgs::MarkerDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ml_msgs::MarkerDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# An marker with reference coordinate frame and timestamp\n"
"Header header\n"
"Marker[] markers              # pose of the detected boards\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ml_msgs/Marker\n"
"# This expresses a marker in a 3D space\n"
"int32 marker_id           # id of the marker detected\n"
"float64 marker_confidence  # confidence that this marker is identified correctly\n"
"\n"
"int32 rows                # number of rows of tags in this marker\n"
"int32 cols                # number of cols of tags in this marker\n"
"\n"
"int32[] tag_ids           # possible ids of the detected marker (empty if no id could be identified)\n"
"float64[] tag_confidence  # confidence of the possible ids in 0 -> 1 (empty if no id could be identified)\n"
"\n"
"geometry_msgs/Pose pose   # pose of the detected marker/fiducial\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ml_msgs::MarkerDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ml_msgs::MarkerDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkerDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ml_msgs::MarkerDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ml_msgs::MarkerDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ml_msgs::Marker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ML_MSGS_MESSAGE_MARKERDETECTION_H
