#!/usr/bin/env python

import sys
import rospy
from egh450g1_code.expanding_script import expander

if __name__ == '__main__':
	# Initialize
	rospy.init_node("expander", anonymous=True)

	try:
		grid = expander()

		rospy.loginfo("[NAV] Grid expander running")

		# Loop here until quit
		rospy.spin()
	except rospy.ROSInterruptException:
		pass
	finally:
		# Shutdown if grid was started successfully
		rospy.loginfo("[NAV] Grid expander shutting down")
		grid.shutdown()
