// Generated by gencpp from file contrail_msgs/CubicSpline.msg
// DO NOT EDIT!


#ifndef CONTRAIL_MSGS_MESSAGE_CUBICSPLINE_H
#define CONTRAIL_MSGS_MESSAGE_CUBICSPLINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace contrail_msgs
{
template <class ContainerAllocator>
struct CubicSpline_
{
  typedef CubicSpline_<ContainerAllocator> Type;

  CubicSpline_()
    : header()
    , start_time()
    , duration()
    , x()
    , y()
    , z()
    , yaw()  {
    }
  CubicSpline_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , start_time()
    , duration()
    , x(_alloc)
    , y(_alloc)
    , z(_alloc)
    , yaw(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _start_time_type;
  _start_time_type start_time;

   typedef ros::Duration _duration_type;
  _duration_type duration;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _z_type;
  _z_type z;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::contrail_msgs::CubicSpline_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::contrail_msgs::CubicSpline_<ContainerAllocator> const> ConstPtr;

}; // struct CubicSpline_

typedef ::contrail_msgs::CubicSpline_<std::allocator<void> > CubicSpline;

typedef boost::shared_ptr< ::contrail_msgs::CubicSpline > CubicSplinePtr;
typedef boost::shared_ptr< ::contrail_msgs::CubicSpline const> CubicSplineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::contrail_msgs::CubicSpline_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::contrail_msgs::CubicSpline_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::contrail_msgs::CubicSpline_<ContainerAllocator1> & lhs, const ::contrail_msgs::CubicSpline_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.start_time == rhs.start_time &&
    lhs.duration == rhs.duration &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::contrail_msgs::CubicSpline_<ContainerAllocator1> & lhs, const ::contrail_msgs::CubicSpline_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace contrail_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::contrail_msgs::CubicSpline_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::contrail_msgs::CubicSpline_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contrail_msgs::CubicSpline_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contrail_msgs::CubicSpline_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contrail_msgs::CubicSpline_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contrail_msgs::CubicSpline_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::contrail_msgs::CubicSpline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6304848616a3ce8d894ccc2d6aae12fc";
  }

  static const char* value(const ::contrail_msgs::CubicSpline_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6304848616a3ce8dULL;
  static const uint64_t static_value2 = 0x894ccc2d6aae12fcULL;
};

template<class ContainerAllocator>
struct DataType< ::contrail_msgs::CubicSpline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "contrail_msgs/CubicSpline";
  }

  static const char* value(const ::contrail_msgs::CubicSpline_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::contrail_msgs::CubicSpline_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# Spline Start Time\n"
"# Defines the time when the spline should begin interpolation\n"
"# If set to Time(0), the spline should start imidiately when recieved\n"
"time start_time\n"
"\n"
"# Duration of the spline\n"
"duration duration\n"
"\n"
"# Knots\n"
"# Each knot is placed evenly throughout the duration of the spline\n"
"float64[] x\n"
"float64[] y\n"
"float64[] z\n"
"float64[] yaw\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::contrail_msgs::CubicSpline_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::contrail_msgs::CubicSpline_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.start_time);
      stream.next(m.duration);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubicSpline_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::contrail_msgs::CubicSpline_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::contrail_msgs::CubicSpline_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start_time);
    s << indent << "duration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.duration);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.z[i]);
    }
    s << indent << "yaw[]" << std::endl;
    for (size_t i = 0; i < v.yaw.size(); ++i)
    {
      s << indent << "  yaw[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.yaw[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTRAIL_MSGS_MESSAGE_CUBICSPLINE_H
