// Generated by gencpp from file contrail_msgs/DiscreteProgress.msg
// DO NOT EDIT!


#ifndef CONTRAIL_MSGS_MESSAGE_DISCRETEPROGRESS_H
#define CONTRAIL_MSGS_MESSAGE_DISCRETEPROGRESS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace contrail_msgs
{
template <class ContainerAllocator>
struct DiscreteProgress_
{
  typedef DiscreteProgress_<ContainerAllocator> Type;

  DiscreteProgress_()
    : header()
    , current(0)
    , progress(0.0)  {
    }
  DiscreteProgress_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current(0)
    , progress(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _current_type;
  _current_type current;

   typedef double _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> const> ConstPtr;

}; // struct DiscreteProgress_

typedef ::contrail_msgs::DiscreteProgress_<std::allocator<void> > DiscreteProgress;

typedef boost::shared_ptr< ::contrail_msgs::DiscreteProgress > DiscreteProgressPtr;
typedef boost::shared_ptr< ::contrail_msgs::DiscreteProgress const> DiscreteProgressConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::contrail_msgs::DiscreteProgress_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::contrail_msgs::DiscreteProgress_<ContainerAllocator1> & lhs, const ::contrail_msgs::DiscreteProgress_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.current == rhs.current &&
    lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::contrail_msgs::DiscreteProgress_<ContainerAllocator1> & lhs, const ::contrail_msgs::DiscreteProgress_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace contrail_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0ce37d53e22567cc5a6951f42cb07aa";
  }

  static const char* value(const ::contrail_msgs::DiscreteProgress_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0ce37d53e22567cULL;
  static const uint64_t static_value2 = 0xc5a6951f42cb07aaULL;
};

template<class ContainerAllocator>
struct DataType< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> >
{
  static const char* value()
  {
    return "contrail_msgs/DiscreteProgress";
  }

  static const char* value(const ::contrail_msgs::DiscreteProgress_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# Latest step in the discrete path completed\n"
"uint32 current\n"
"\n"
"# Overall path progess (1.0 = 100%)\n"
"float64 progress\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::contrail_msgs::DiscreteProgress_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current);
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiscreteProgress_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::contrail_msgs::DiscreteProgress_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::contrail_msgs::DiscreteProgress_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.current);
    s << indent << "progress: ";
    Printer<double>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTRAIL_MSGS_MESSAGE_DISCRETEPROGRESS_H
