// Generated by gencpp from file contrail_msgs/SetTracking.msg
// DO NOT EDIT!


#ifndef CONTRAIL_MSGS_MESSAGE_SETTRACKING_H
#define CONTRAIL_MSGS_MESSAGE_SETTRACKING_H

#include <ros/service_traits.h>


#include <contrail_msgs/SetTrackingRequest.h>
#include <contrail_msgs/SetTrackingResponse.h>


namespace contrail_msgs
{

struct SetTracking
{

typedef SetTrackingRequest Request;
typedef SetTrackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTracking
} // namespace contrail_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::contrail_msgs::SetTracking > {
  static const char* value()
  {
    return "fcc46c426eb0b77856610784df76e9f8";
  }

  static const char* value(const ::contrail_msgs::SetTracking&) { return value(); }
};

template<>
struct DataType< ::contrail_msgs::SetTracking > {
  static const char* value()
  {
    return "contrail_msgs/SetTracking";
  }

  static const char* value(const ::contrail_msgs::SetTracking&) { return value(); }
};


// service_traits::MD5Sum< ::contrail_msgs::SetTrackingRequest> should match
// service_traits::MD5Sum< ::contrail_msgs::SetTracking >
template<>
struct MD5Sum< ::contrail_msgs::SetTrackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::contrail_msgs::SetTracking >::value();
  }
  static const char* value(const ::contrail_msgs::SetTrackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::contrail_msgs::SetTrackingRequest> should match
// service_traits::DataType< ::contrail_msgs::SetTracking >
template<>
struct DataType< ::contrail_msgs::SetTrackingRequest>
{
  static const char* value()
  {
    return DataType< ::contrail_msgs::SetTracking >::value();
  }
  static const char* value(const ::contrail_msgs::SetTrackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::contrail_msgs::SetTrackingResponse> should match
// service_traits::MD5Sum< ::contrail_msgs::SetTracking >
template<>
struct MD5Sum< ::contrail_msgs::SetTrackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::contrail_msgs::SetTracking >::value();
  }
  static const char* value(const ::contrail_msgs::SetTrackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::contrail_msgs::SetTrackingResponse> should match
// service_traits::DataType< ::contrail_msgs::SetTracking >
template<>
struct DataType< ::contrail_msgs::SetTrackingResponse>
{
  static const char* value()
  {
    return DataType< ::contrail_msgs::SetTracking >::value();
  }
  static const char* value(const ::contrail_msgs::SetTrackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTRAIL_MSGS_MESSAGE_SETTRACKING_H
