// Generated by gencpp from file contrail_msgs/Waypoint.msg
// DO NOT EDIT!


#ifndef CONTRAIL_MSGS_MESSAGE_WAYPOINT_H
#define CONTRAIL_MSGS_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace contrail_msgs
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : position()
    , yaw(0.0)  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::contrail_msgs::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::contrail_msgs::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::contrail_msgs::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::contrail_msgs::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::contrail_msgs::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::contrail_msgs::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::contrail_msgs::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::contrail_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::contrail_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::contrail_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::contrail_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace contrail_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::contrail_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::contrail_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contrail_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contrail_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contrail_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contrail_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::contrail_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cc04ac3ba6c1f0f2caa721fb8f71842";
  }

  static const char* value(const ::contrail_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cc04ac3ba6c1f0fULL;
  static const uint64_t static_value2 = 0x2caa721fb8f71842ULL;
};

template<class ContainerAllocator>
struct DataType< ::contrail_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "contrail_msgs/Waypoint";
  }

  static const char* value(const ::contrail_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::contrail_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::contrail_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::contrail_msgs::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::contrail_msgs::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::contrail_msgs::Waypoint_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTRAIL_MSGS_MESSAGE_WAYPOINT_H
