// Generated by gencpp from file contrail_msgs/WaypointList.msg
// DO NOT EDIT!


#ifndef CONTRAIL_MSGS_MESSAGE_WAYPOINTLIST_H
#define CONTRAIL_MSGS_MESSAGE_WAYPOINTLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <contrail_msgs/Waypoint.h>

namespace contrail_msgs
{
template <class ContainerAllocator>
struct WaypointList_
{
  typedef WaypointList_<ContainerAllocator> Type;

  WaypointList_()
    : header()
    , waypoints()  {
    }
  WaypointList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::contrail_msgs::Waypoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::contrail_msgs::Waypoint_<ContainerAllocator> >::other >  _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::contrail_msgs::WaypointList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::contrail_msgs::WaypointList_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointList_

typedef ::contrail_msgs::WaypointList_<std::allocator<void> > WaypointList;

typedef boost::shared_ptr< ::contrail_msgs::WaypointList > WaypointListPtr;
typedef boost::shared_ptr< ::contrail_msgs::WaypointList const> WaypointListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::contrail_msgs::WaypointList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::contrail_msgs::WaypointList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::contrail_msgs::WaypointList_<ContainerAllocator1> & lhs, const ::contrail_msgs::WaypointList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::contrail_msgs::WaypointList_<ContainerAllocator1> & lhs, const ::contrail_msgs::WaypointList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace contrail_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::contrail_msgs::WaypointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::contrail_msgs::WaypointList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contrail_msgs::WaypointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contrail_msgs::WaypointList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contrail_msgs::WaypointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contrail_msgs::WaypointList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::contrail_msgs::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d52cc0d9658fd4fc6343be220e396b2";
  }

  static const char* value(const ::contrail_msgs::WaypointList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d52cc0d9658fd4fULL;
  static const uint64_t static_value2 = 0xc6343be220e396b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::contrail_msgs::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "contrail_msgs/WaypointList";
  }

  static const char* value(const ::contrail_msgs::WaypointList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::contrail_msgs::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"contrail_msgs/Waypoint[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: contrail_msgs/Waypoint\n"
"geometry_msgs/Point position\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::contrail_msgs::WaypointList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::contrail_msgs::WaypointList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::contrail_msgs::WaypointList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::contrail_msgs::WaypointList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::contrail_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTRAIL_MSGS_MESSAGE_WAYPOINTLIST_H
