#!/usr/bin/env python

import sys

from rqt_contrail_planner.planner import Planner
from rqt_gui.main import Main

plugin = 'rqt_contrail_planner'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
