//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the mavel package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __mavel__MAVELPARAMSCONFIG_H__
#define __mavel__MAVELPARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace mavel
{
  class MavelParamsConfigStatics;

  class MavelParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(MavelParamsConfig &config, const MavelParamsConfig &max, const MavelParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const MavelParamsConfig &config1, const MavelParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, MavelParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const MavelParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MavelParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const MavelParamsConfig &config) const = 0;
      virtual void getValue(const MavelParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T MavelParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T MavelParamsConfig::* field;

      virtual void clamp(MavelParamsConfig &config, const MavelParamsConfig &max, const MavelParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const MavelParamsConfig &config1, const MavelParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, MavelParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const MavelParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MavelParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const MavelParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const MavelParamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, MavelParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, MavelParamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<MavelParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(MavelParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class OPERATION
{
  public:
    OPERATION()
    {
      state = true;
      name = "Operation";
    }

    void setParams(MavelParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("allow_timeout_position"==(*_i)->name){allow_timeout_position = boost::any_cast<bool>(val);}
        if("allow_controller_reset"==(*_i)->name){allow_controller_reset = boost::any_cast<bool>(val);}
        if("use_tracking_control"==(*_i)->name){use_tracking_control = boost::any_cast<bool>(val);}
      }
    }

    bool allow_timeout_position;
bool allow_controller_reset;
bool use_tracking_control;

    bool state;
    std::string name;

    
}operation;

class CONTROL
{
  public:
    CONTROL()
    {
      state = true;
      name = "Control";
    }

    void setParams(MavelParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("tilt_max"==(*_i)->name){tilt_max = boost::any_cast<double>(val);}
        if("throttle_min"==(*_i)->name){throttle_min = boost::any_cast<double>(val);}
        if("throttle_mid"==(*_i)->name){throttle_mid = boost::any_cast<double>(val);}
        if("throttle_max"==(*_i)->name){throttle_max = boost::any_cast<double>(val);}
      }
    }

    double tilt_max;
double throttle_min;
double throttle_mid;
double throttle_max;

    bool state;
    std::string name;

    
}control;

class FAILSAFE
{
  public:
    FAILSAFE()
    {
      state = true;
      name = "Failsafe";
    }

    void setParams(MavelParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("failsafe_output_on_fatal"==(*_i)->name){failsafe_output_on_fatal = boost::any_cast<bool>(val);}
        if("failsafe_land_vel"==(*_i)->name){failsafe_land_vel = boost::any_cast<double>(val);}
      }
    }

    bool failsafe_output_on_fatal;
double failsafe_land_vel;

    bool state;
    std::string name;

    
}failsafe;

}groups;



//#line 10 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      bool allow_timeout_position;
//#line 11 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      bool allow_controller_reset;
//#line 12 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      bool use_tracking_control;
//#line 15 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      double tilt_max;
//#line 16 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      double throttle_min;
//#line 17 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      double throttle_mid;
//#line 18 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      double throttle_max;
//#line 24 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      bool failsafe_output_on_fatal;
//#line 25 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      double failsafe_land_vel;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("MavelParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const MavelParamsConfig &__max__ = __getMax__();
      const MavelParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const MavelParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const MavelParamsConfig &__getDefault__();
    static const MavelParamsConfig &__getMax__();
    static const MavelParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const MavelParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void MavelParamsConfig::ParamDescription<std::string>::clamp(MavelParamsConfig &config, const MavelParamsConfig &max, const MavelParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class MavelParamsConfigStatics
  {
    friend class MavelParamsConfig;

    MavelParamsConfigStatics()
    {
MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT, MavelParamsConfig> Default("Default", "", 0, 0, true, &MavelParamsConfig::groups);
MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT::OPERATION, MavelParamsConfig::DEFAULT> Operation("Operation", "", 0, 1, true, &MavelParamsConfig::DEFAULT::operation);
//#line 10 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __min__.allow_timeout_position = 0;
//#line 10 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __max__.allow_timeout_position = 1;
//#line 10 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __default__.allow_timeout_position = 0;
//#line 10 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      Operation.abstract_parameters.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<bool>("allow_timeout_position", "bool", 0, "Allows timeout on position-only reference inputs", "", &MavelParamsConfig::allow_timeout_position)));
//#line 10 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __param_descriptions__.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<bool>("allow_timeout_position", "bool", 0, "Allows timeout on position-only reference inputs", "", &MavelParamsConfig::allow_timeout_position)));
//#line 11 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __min__.allow_controller_reset = 0;
//#line 11 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __max__.allow_controller_reset = 1;
//#line 11 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __default__.allow_controller_reset = 0;
//#line 11 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      Operation.abstract_parameters.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<bool>("allow_controller_reset", "bool", 0, "Allows for mavel to reset to the pre-armed state if system is disarmed", "", &MavelParamsConfig::allow_controller_reset)));
//#line 11 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __param_descriptions__.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<bool>("allow_controller_reset", "bool", 0, "Allows for mavel to reset to the pre-armed state if system is disarmed", "", &MavelParamsConfig::allow_controller_reset)));
//#line 12 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __min__.use_tracking_control = 0;
//#line 12 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __max__.use_tracking_control = 1;
//#line 12 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __default__.use_tracking_control = 0;
//#line 12 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      Operation.abstract_parameters.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<bool>("use_tracking_control", "bool", 0, "Switches the control scheme to a tracking controller control", "", &MavelParamsConfig::use_tracking_control)));
//#line 12 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __param_descriptions__.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<bool>("use_tracking_control", "bool", 0, "Switches the control scheme to a tracking controller control", "", &MavelParamsConfig::use_tracking_control)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Operation.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(MavelParamsConfig::AbstractGroupDescriptionConstPtr(new MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT::OPERATION, MavelParamsConfig::DEFAULT>(Operation)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(MavelParamsConfig::AbstractGroupDescriptionConstPtr(new MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT::OPERATION, MavelParamsConfig::DEFAULT>(Operation)));
MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT::CONTROL, MavelParamsConfig::DEFAULT> Control("Control", "", 0, 2, true, &MavelParamsConfig::DEFAULT::control);
//#line 15 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __min__.tilt_max = 0.0;
//#line 15 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __max__.tilt_max = std::numeric_limits<double>::infinity();
//#line 15 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __default__.tilt_max = 0.39;
//#line 15 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      Control.abstract_parameters.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("tilt_max", "double", 0, "Maximum tilt angle that can be commanded (rad)", "", &MavelParamsConfig::tilt_max)));
//#line 15 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __param_descriptions__.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("tilt_max", "double", 0, "Maximum tilt angle that can be commanded (rad)", "", &MavelParamsConfig::tilt_max)));
//#line 16 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __min__.throttle_min = 0.0;
//#line 16 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __max__.throttle_min = 1.0;
//#line 16 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __default__.throttle_min = 0.1;
//#line 16 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      Control.abstract_parameters.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("throttle_min", "double", 0, "Minimum throttle that can be commanded (%)", "", &MavelParamsConfig::throttle_min)));
//#line 16 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __param_descriptions__.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("throttle_min", "double", 0, "Minimum throttle that can be commanded (%)", "", &MavelParamsConfig::throttle_min)));
//#line 17 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __min__.throttle_mid = 0.0;
//#line 17 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __max__.throttle_mid = 1.0;
//#line 17 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __default__.throttle_mid = 0.5;
//#line 17 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      Control.abstract_parameters.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("throttle_mid", "double", 0, "Midpoint throttle required for stable hover (%)", "", &MavelParamsConfig::throttle_mid)));
//#line 17 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __param_descriptions__.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("throttle_mid", "double", 0, "Midpoint throttle required for stable hover (%)", "", &MavelParamsConfig::throttle_mid)));
//#line 18 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __min__.throttle_max = 0.0;
//#line 18 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __max__.throttle_max = 1.0;
//#line 18 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __default__.throttle_max = 0.9;
//#line 18 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      Control.abstract_parameters.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("throttle_max", "double", 0, "Maximum throttle that can be commanded (%)", "", &MavelParamsConfig::throttle_max)));
//#line 18 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __param_descriptions__.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("throttle_max", "double", 0, "Maximum throttle that can be commanded (%)", "", &MavelParamsConfig::throttle_max)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Control.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(MavelParamsConfig::AbstractGroupDescriptionConstPtr(new MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT::CONTROL, MavelParamsConfig::DEFAULT>(Control)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(MavelParamsConfig::AbstractGroupDescriptionConstPtr(new MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT::CONTROL, MavelParamsConfig::DEFAULT>(Control)));
MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT::FAILSAFE, MavelParamsConfig::DEFAULT> Failsafe("Failsafe", "", 0, 3, true, &MavelParamsConfig::DEFAULT::failsafe);
//#line 24 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __min__.failsafe_output_on_fatal = 0;
//#line 24 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __max__.failsafe_output_on_fatal = 1;
//#line 24 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __default__.failsafe_output_on_fatal = 0;
//#line 24 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      Failsafe.abstract_parameters.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<bool>("failsafe_output_on_fatal", "bool", 0, "Enables output of the controller if a hard failsafe is declared (default is False: mavel will stop outputting reference commands)", "", &MavelParamsConfig::failsafe_output_on_fatal)));
//#line 24 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __param_descriptions__.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<bool>("failsafe_output_on_fatal", "bool", 0, "Enables output of the controller if a hard failsafe is declared (default is False: mavel will stop outputting reference commands)", "", &MavelParamsConfig::failsafe_output_on_fatal)));
//#line 25 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __min__.failsafe_land_vel = -std::numeric_limits<double>::infinity();
//#line 25 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __max__.failsafe_land_vel = 0.0;
//#line 25 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __default__.failsafe_land_vel = -0.2;
//#line 25 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      Failsafe.abstract_parameters.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("failsafe_land_vel", "double", 0, "Landing velocity if input reference is lost, but odometry is still available", "", &MavelParamsConfig::failsafe_land_vel)));
//#line 25 "/home/griff/catkin_ws/src/mavel/cfg/MavelParams.cfg"
      __param_descriptions__.push_back(MavelParamsConfig::AbstractParamDescriptionConstPtr(new MavelParamsConfig::ParamDescription<double>("failsafe_land_vel", "double", 0, "Landing velocity if input reference is lost, but odometry is still available", "", &MavelParamsConfig::failsafe_land_vel)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Failsafe.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(MavelParamsConfig::AbstractGroupDescriptionConstPtr(new MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT::FAILSAFE, MavelParamsConfig::DEFAULT>(Failsafe)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(MavelParamsConfig::AbstractGroupDescriptionConstPtr(new MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT::FAILSAFE, MavelParamsConfig::DEFAULT>(Failsafe)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(MavelParamsConfig::AbstractGroupDescriptionConstPtr(new MavelParamsConfig::GroupDescription<MavelParamsConfig::DEFAULT, MavelParamsConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<MavelParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<MavelParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<MavelParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    MavelParamsConfig __max__;
    MavelParamsConfig __min__;
    MavelParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const MavelParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static MavelParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &MavelParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const MavelParamsConfig &MavelParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const MavelParamsConfig &MavelParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const MavelParamsConfig &MavelParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<MavelParamsConfig::AbstractParamDescriptionConstPtr> &MavelParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<MavelParamsConfig::AbstractGroupDescriptionConstPtr> &MavelParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const MavelParamsConfigStatics *MavelParamsConfig::__get_statics__()
  {
    const static MavelParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = MavelParamsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MAVELPARAMSRECONFIGURATOR_H__
