//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the ml_detector package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __ml_detector__DETECTORPARAMSCONFIG_H__
#define __ml_detector__DETECTORPARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace ml_detector
{
  class DetectorParamsConfigStatics;

  class DetectorParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(DetectorParamsConfig &config, const DetectorParamsConfig &max, const DetectorParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const DetectorParamsConfig &config1, const DetectorParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, DetectorParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const DetectorParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DetectorParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const DetectorParamsConfig &config) const = 0;
      virtual void getValue(const DetectorParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T DetectorParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T DetectorParamsConfig::* field;

      virtual void clamp(DetectorParamsConfig &config, const DetectorParamsConfig &max, const DetectorParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const DetectorParamsConfig &config1, const DetectorParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, DetectorParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const DetectorParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DetectorParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const DetectorParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const DetectorParamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, DetectorParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, DetectorParamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<DetectorParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(DetectorParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("adaptive_thresh_win_size_min"==(*_i)->name){adaptive_thresh_win_size_min = boost::any_cast<int>(val);}
        if("adaptive_thresh_win_size_max"==(*_i)->name){adaptive_thresh_win_size_max = boost::any_cast<int>(val);}
        if("adaptive_thresh_win_size_step"==(*_i)->name){adaptive_thresh_win_size_step = boost::any_cast<int>(val);}
        if("adaptive_thresh_constant"==(*_i)->name){adaptive_thresh_constant = boost::any_cast<double>(val);}
        if("min_marker_perimeter_rate"==(*_i)->name){min_marker_perimeter_rate = boost::any_cast<double>(val);}
        if("max_marker_perimeter_rate"==(*_i)->name){max_marker_perimeter_rate = boost::any_cast<double>(val);}
        if("polygonal_approx_accuracy_rate"==(*_i)->name){polygonal_approx_accuracy_rate = boost::any_cast<double>(val);}
        if("min_corner_distance_rate"==(*_i)->name){min_corner_distance_rate = boost::any_cast<double>(val);}
        if("min_marker_distance_rate"==(*_i)->name){min_marker_distance_rate = boost::any_cast<double>(val);}
        if("min_distance_to_border"==(*_i)->name){min_distance_to_border = boost::any_cast<int>(val);}
        if("marker_border_bits"==(*_i)->name){marker_border_bits = boost::any_cast<int>(val);}
        if("min_otsu_std_dev"==(*_i)->name){min_otsu_std_dev = boost::any_cast<double>(val);}
        if("perspective_remove_pixel_per_cell"==(*_i)->name){perspective_remove_pixel_per_cell = boost::any_cast<int>(val);}
        if("perspective_remove_ignored_margin_per_cell"==(*_i)->name){perspective_remove_ignored_margin_per_cell = boost::any_cast<double>(val);}
        if("max_erroneous_bits_in_border_rate"==(*_i)->name){max_erroneous_bits_in_border_rate = boost::any_cast<int>(val);}
        if("error_correction_rate"==(*_i)->name){error_correction_rate = boost::any_cast<double>(val);}
        if("corner_refinement_method"==(*_i)->name){corner_refinement_method = boost::any_cast<int>(val);}
        if("corner_refinement_win_size"==(*_i)->name){corner_refinement_win_size = boost::any_cast<int>(val);}
        if("corner_refinement_max_iterations"==(*_i)->name){corner_refinement_max_iterations = boost::any_cast<int>(val);}
        if("corner_refinement_min_accuracy"==(*_i)->name){corner_refinement_min_accuracy = boost::any_cast<double>(val);}
      }
    }

    int adaptive_thresh_win_size_min;
int adaptive_thresh_win_size_max;
int adaptive_thresh_win_size_step;
double adaptive_thresh_constant;
double min_marker_perimeter_rate;
double max_marker_perimeter_rate;
double polygonal_approx_accuracy_rate;
double min_corner_distance_rate;
double min_marker_distance_rate;
int min_distance_to_border;
int marker_border_bits;
double min_otsu_std_dev;
int perspective_remove_pixel_per_cell;
double perspective_remove_ignored_margin_per_cell;
int max_erroneous_bits_in_border_rate;
double error_correction_rate;
int corner_refinement_method;
int corner_refinement_win_size;
int corner_refinement_max_iterations;
double corner_refinement_min_accuracy;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int adaptive_thresh_win_size_min;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int adaptive_thresh_win_size_max;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int adaptive_thresh_win_size_step;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double adaptive_thresh_constant;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_marker_perimeter_rate;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_marker_perimeter_rate;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double polygonal_approx_accuracy_rate;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_corner_distance_rate;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_marker_distance_rate;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_distance_to_border;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int marker_border_bits;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_otsu_std_dev;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int perspective_remove_pixel_per_cell;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double perspective_remove_ignored_margin_per_cell;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_erroneous_bits_in_border_rate;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double error_correction_rate;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int corner_refinement_method;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int corner_refinement_win_size;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int corner_refinement_max_iterations;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double corner_refinement_min_accuracy;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("DetectorParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const DetectorParamsConfig &__max__ = __getMax__();
      const DetectorParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const DetectorParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const DetectorParamsConfig &__getDefault__();
    static const DetectorParamsConfig &__getMax__();
    static const DetectorParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const DetectorParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void DetectorParamsConfig::ParamDescription<std::string>::clamp(DetectorParamsConfig &config, const DetectorParamsConfig &max, const DetectorParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class DetectorParamsConfigStatics
  {
    friend class DetectorParamsConfig;

    DetectorParamsConfigStatics()
    {
DetectorParamsConfig::GroupDescription<DetectorParamsConfig::DEFAULT, DetectorParamsConfig> Default("Default", "", 0, 0, true, &DetectorParamsConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.adaptive_thresh_win_size_min = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.adaptive_thresh_win_size_min = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.adaptive_thresh_win_size_min = 3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("adaptive_thresh_win_size_min", "int", 0, "", "", &DetectorParamsConfig::adaptive_thresh_win_size_min)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("adaptive_thresh_win_size_min", "int", 0, "", "", &DetectorParamsConfig::adaptive_thresh_win_size_min)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.adaptive_thresh_win_size_max = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.adaptive_thresh_win_size_max = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.adaptive_thresh_win_size_max = 23;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("adaptive_thresh_win_size_max", "int", 0, "", "", &DetectorParamsConfig::adaptive_thresh_win_size_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("adaptive_thresh_win_size_max", "int", 0, "", "", &DetectorParamsConfig::adaptive_thresh_win_size_max)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.adaptive_thresh_win_size_step = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.adaptive_thresh_win_size_step = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.adaptive_thresh_win_size_step = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("adaptive_thresh_win_size_step", "int", 0, "", "", &DetectorParamsConfig::adaptive_thresh_win_size_step)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("adaptive_thresh_win_size_step", "int", 0, "", "", &DetectorParamsConfig::adaptive_thresh_win_size_step)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.adaptive_thresh_constant = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.adaptive_thresh_constant = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.adaptive_thresh_constant = 7.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("adaptive_thresh_constant", "double", 0, "", "", &DetectorParamsConfig::adaptive_thresh_constant)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("adaptive_thresh_constant", "double", 0, "", "", &DetectorParamsConfig::adaptive_thresh_constant)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_marker_perimeter_rate = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_marker_perimeter_rate = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_marker_perimeter_rate = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("min_marker_perimeter_rate", "double", 0, "", "", &DetectorParamsConfig::min_marker_perimeter_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("min_marker_perimeter_rate", "double", 0, "", "", &DetectorParamsConfig::min_marker_perimeter_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_marker_perimeter_rate = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_marker_perimeter_rate = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_marker_perimeter_rate = 4.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("max_marker_perimeter_rate", "double", 0, "", "", &DetectorParamsConfig::max_marker_perimeter_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("max_marker_perimeter_rate", "double", 0, "", "", &DetectorParamsConfig::max_marker_perimeter_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.polygonal_approx_accuracy_rate = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.polygonal_approx_accuracy_rate = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.polygonal_approx_accuracy_rate = 0.0075;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("polygonal_approx_accuracy_rate", "double", 0, "", "", &DetectorParamsConfig::polygonal_approx_accuracy_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("polygonal_approx_accuracy_rate", "double", 0, "", "", &DetectorParamsConfig::polygonal_approx_accuracy_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_corner_distance_rate = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_corner_distance_rate = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_corner_distance_rate = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("min_corner_distance_rate", "double", 0, "", "", &DetectorParamsConfig::min_corner_distance_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("min_corner_distance_rate", "double", 0, "", "", &DetectorParamsConfig::min_corner_distance_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_marker_distance_rate = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_marker_distance_rate = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_marker_distance_rate = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("min_marker_distance_rate", "double", 0, "", "", &DetectorParamsConfig::min_marker_distance_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("min_marker_distance_rate", "double", 0, "", "", &DetectorParamsConfig::min_marker_distance_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_distance_to_border = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_distance_to_border = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_distance_to_border = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("min_distance_to_border", "int", 0, "", "", &DetectorParamsConfig::min_distance_to_border)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("min_distance_to_border", "int", 0, "", "", &DetectorParamsConfig::min_distance_to_border)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.marker_border_bits = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.marker_border_bits = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.marker_border_bits = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("marker_border_bits", "int", 0, "", "", &DetectorParamsConfig::marker_border_bits)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("marker_border_bits", "int", 0, "", "", &DetectorParamsConfig::marker_border_bits)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_otsu_std_dev = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_otsu_std_dev = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_otsu_std_dev = 5.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("min_otsu_std_dev", "double", 0, "", "", &DetectorParamsConfig::min_otsu_std_dev)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("min_otsu_std_dev", "double", 0, "", "", &DetectorParamsConfig::min_otsu_std_dev)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.perspective_remove_pixel_per_cell = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.perspective_remove_pixel_per_cell = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.perspective_remove_pixel_per_cell = 8;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("perspective_remove_pixel_per_cell", "int", 0, "", "", &DetectorParamsConfig::perspective_remove_pixel_per_cell)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("perspective_remove_pixel_per_cell", "int", 0, "", "", &DetectorParamsConfig::perspective_remove_pixel_per_cell)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.perspective_remove_ignored_margin_per_cell = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.perspective_remove_ignored_margin_per_cell = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.perspective_remove_ignored_margin_per_cell = 0.13;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("perspective_remove_ignored_margin_per_cell", "double", 0, "", "", &DetectorParamsConfig::perspective_remove_ignored_margin_per_cell)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("perspective_remove_ignored_margin_per_cell", "double", 0, "", "", &DetectorParamsConfig::perspective_remove_ignored_margin_per_cell)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_erroneous_bits_in_border_rate = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_erroneous_bits_in_border_rate = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_erroneous_bits_in_border_rate = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("max_erroneous_bits_in_border_rate", "int", 0, "", "", &DetectorParamsConfig::max_erroneous_bits_in_border_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("max_erroneous_bits_in_border_rate", "int", 0, "", "", &DetectorParamsConfig::max_erroneous_bits_in_border_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.error_correction_rate = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.error_correction_rate = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.error_correction_rate = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("error_correction_rate", "double", 0, "", "", &DetectorParamsConfig::error_correction_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("error_correction_rate", "double", 0, "", "", &DetectorParamsConfig::error_correction_rate)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.corner_refinement_method = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.corner_refinement_method = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.corner_refinement_method = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("corner_refinement_method", "int", 0, "", "", &DetectorParamsConfig::corner_refinement_method)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("corner_refinement_method", "int", 0, "", "", &DetectorParamsConfig::corner_refinement_method)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.corner_refinement_win_size = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.corner_refinement_win_size = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.corner_refinement_win_size = 5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("corner_refinement_win_size", "int", 0, "", "", &DetectorParamsConfig::corner_refinement_win_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("corner_refinement_win_size", "int", 0, "", "", &DetectorParamsConfig::corner_refinement_win_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.corner_refinement_max_iterations = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.corner_refinement_max_iterations = 2147483647;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.corner_refinement_max_iterations = 30;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("corner_refinement_max_iterations", "int", 0, "", "", &DetectorParamsConfig::corner_refinement_max_iterations)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<int>("corner_refinement_max_iterations", "int", 0, "", "", &DetectorParamsConfig::corner_refinement_max_iterations)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.corner_refinement_min_accuracy = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.corner_refinement_min_accuracy = std::numeric_limits<double>::infinity();
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.corner_refinement_min_accuracy = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("corner_refinement_min_accuracy", "double", 0, "", "", &DetectorParamsConfig::corner_refinement_min_accuracy)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DetectorParamsConfig::AbstractParamDescriptionConstPtr(new DetectorParamsConfig::ParamDescription<double>("corner_refinement_min_accuracy", "double", 0, "", "", &DetectorParamsConfig::corner_refinement_min_accuracy)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(DetectorParamsConfig::AbstractGroupDescriptionConstPtr(new DetectorParamsConfig::GroupDescription<DetectorParamsConfig::DEFAULT, DetectorParamsConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<DetectorParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<DetectorParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<DetectorParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    DetectorParamsConfig __max__;
    DetectorParamsConfig __min__;
    DetectorParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const DetectorParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static DetectorParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &DetectorParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const DetectorParamsConfig &DetectorParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const DetectorParamsConfig &DetectorParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const DetectorParamsConfig &DetectorParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<DetectorParamsConfig::AbstractParamDescriptionConstPtr> &DetectorParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<DetectorParamsConfig::AbstractGroupDescriptionConstPtr> &DetectorParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const DetectorParamsConfigStatics *DetectorParamsConfig::__get_statics__()
  {
    const static DetectorParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = DetectorParamsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __DETECTORPARAMSRECONFIGURATOR_H__
