(cl:defpackage contrail_manager-msg
  (:use )
  (:export
   "<TRAJECTORYACTION>"
   "TRAJECTORYACTION"
   "<TRAJECTORYACTIONFEEDBACK>"
   "TRAJECTORYACTIONFEEDBACK"
   "<TRAJECTORYACTIONGOAL>"
   "TRAJECTORYACTIONGOAL"
   "<TRAJECTORYACTIONRESULT>"
   "TRAJECTORYACTIONRESULT"
   "<TRAJECTORYFEEDBACK>"
   "TRAJECTORYFEEDBACK"
   "<TRAJECTORYGOAL>"
   "TRAJECTORYGOAL"
   "<TRAJECTORYRESULT>"
   "TRAJECTORYRESULT"
  ))

